# Generated by Django 5.0.6 on 2024-06-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paragraphs.paragraph')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paragraphs.word')),
            ],
            options={
                'unique_together': {('paragraph', 'word')},
            },
        ),
    ]
