# Generated by Django 5.0.6 on 2024-06-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_details_delete_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
